export const configuration = () => {
  const {
    NODE_ENV,
    PORT,
    DB_HOST,
    DB_PORT,
    DB_NAME,
    DB_USERNAME,
    DB_PASSWORD,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_SECURE,
    EMAIL_USERNAME,
    EMAIL_PASSWORD,
    EMAIL_FROM,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    GOOGLE_REDIRECT_URL,
    JWT_ACCESS_SECRET,
    JWT_ACCESS_EXPIRATION,
    JWT_REFRESH_SECRET,
    JWT_REFRESH_EXPIRATION,
    FRONTEND_URL,
    EMAIL_VERIFICATION_URL,
    RESET_PASSWORD_URL,
  } = process.env;

  return {
    database: {
      host: DB_HOST,
      port: parseInt(DB_PORT, 10) || 3306,
      name: DB_NAME,
      username: DB_USERNAME,
      password: DB_PASSWORD,
    },
    email: {
      host: EMAIL_HOST,
      port: parseInt(EMAIL_PORT, 10) || 587,
      secure: EMAIL_SECURE === 'true',
      username: EMAIL_USERNAME,
      password: EMAIL_PASSWORD,
      from: EMAIL_FROM,
    },
    google: {
      clientId: GOOGLE_CLIENT_ID,
      clientSecret: GOOGLE_CLIENT_SECRET,
      callbackUrl: GOOGLE_CALLBACK_URL,
      redirectUrl: GOOGLE_REDIRECT_URL,
    },
    jwt: {
      accessSecret: JWT_ACCESS_SECRET,
      accessExpiration: JWT_ACCESS_EXPIRATION,
      refreshSecret: JWT_REFRESH_SECRET,
      refreshExpiration: JWT_REFRESH_EXPIRATION,
    },
    server: {
      isProduction: NODE_ENV === 'production',
      isDevelopment: NODE_ENV === 'development',
      port: parseInt(PORT, 10) || 3000,
      frontendUrl: FRONTEND_URL,
      emailVerificationUrl: EMAIL_VERIFICATION_URL,
      resetPasswordUrl: RESET_PASSWORD_URL,
    },
  };
};
